import React, { useEffect, useState } from 'react';
import { fetchAdminLogs, fetchApiStats } from '../../services/api';
import { PromptLogItem, ApiUsageStats } from '../../types';
import { Terminal, Cpu, Clock, CheckCircle, Copy, Check, Sparkles } from 'lucide-react';

export const AdminPromptLogsView: React.FC = () => {
  const [logs, setLogs] = useState<PromptLogItem[]>([]);
  const [stats, setStats] = useState<ApiUsageStats | null>(null);
  const [copiedId, setCopiedId] = useState<number | null>(null);

  useEffect(() => {
    fetchAdminLogs().then(setLogs);
    fetchApiStats().then(setStats);
  }, []);

  const copyPrompt = (id: number, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-12">
      
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center space-x-2">
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">
              Gemini AI Prompt Engineering Audit Logs
            </h2>
            <span className="text-[10px] font-black uppercase bg-amber-500/10 text-amber-600 border border-amber-500/20 px-2 py-0.5 rounded">
              ADMIN ONLY
            </span>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Inspect compiled industrial studio prompts generated by Python backend prompt engine
          </p>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white dark:bg-slate-900 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-soft">
          <div className="text-xs font-bold text-slate-400">TOTAL API CALLS</div>
          <div className="text-2xl font-black text-slate-900 dark:text-white mt-1">
            {stats?.total_generations || logs.length || 0}
          </div>
        </div>
        <div className="bg-white dark:bg-slate-900 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-soft">
          <div className="text-xs font-bold text-slate-400">DIRECT GEMINI CALLS</div>
          <div className="text-2xl font-black text-pegma-red mt-1">
            {stats?.gemini_api_calls || 0}
          </div>
        </div>
        <div className="bg-white dark:bg-slate-900 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-soft">
          <div className="text-xs font-bold text-slate-400">KEY STATUS</div>
          <div className="text-base font-bold text-emerald-600 mt-1">
            {stats?.active_key ? "Configured & Active" : "Visualizer Engine Fallback"}
          </div>
        </div>
      </div>

      {/* Logs Table / List */}
      <div className="space-y-3">
        {logs.length === 0 ? (
          <div className="p-8 text-center text-xs text-slate-400 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800">
            No audit logs recorded yet. Generate images to populate logs.
          </div>
        ) : (
          logs.map((log) => (
            <div
              key={log.id}
              className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-4 shadow-soft space-y-2 font-mono text-xs"
            >
              <div className="flex items-center justify-between font-sans">
                <div className="flex items-center space-x-2">
                  <span className="font-bold text-slate-900 dark:text-white">
                    LOG #{log.id}
                  </span>
                  <span className="text-[10px] bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded text-slate-500">
                    {new Date(log.timestamp).toLocaleTimeString()}
                  </span>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${
                    log.status === 'success' ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-100 text-blue-700'
                  }`}>
                    {log.status.toUpperCase()}
                  </span>
                </div>

                <div className="flex items-center space-x-3 text-slate-400 font-sans text-xs">
                  <span>{log.latency_ms} ms</span>
                  <button
                    onClick={() => copyPrompt(log.id, log.compiled_prompt)}
                    className="p-1 hover:bg-slate-100 dark:hover:bg-slate-800 rounded text-slate-600 dark:text-slate-300"
                    title="Copy Prompt"
                  >
                    {copiedId === log.id ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                </div>
              </div>

              {/* Prompt Text Box */}
              <div className="p-3 bg-slate-950 text-slate-200 rounded-xl leading-relaxed text-[11px] overflow-x-auto">
                {log.compiled_prompt}
              </div>
            </div>
          ))
        )}
      </div>

    </div>
  );
};
